# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build Image Without buildx.
    run: once
    cmds:
      - >-
        docker build
        --platform={{.DOCKER_PLATFORMS}}
        --file Dockerfile
        --tag {{.DOCKER_ORGANIZATION}}/{{.DOCKER_IMAGE_NAME}}:{{.DOCKER_TAG}} .
        --build-arg VERSION={{.DOCKER_TAG}}
    vars:
      DOCKER_TAG: latest
      DOCKER_IMAGE_NAME: pandoc
      DOCKER_PLATFORMS: linux/amd64

  publish:
    desc: Publish Image with buildx .
    run: once
    cmds:
      - >-
        docker buildx build --platform={{.DOCKER_PLATFORMS}}
        --file Dockerfile
        --tag {{.DOCKER_ORGANIZATION}}/{{.DOCKER_IMAGE_NAME}}:{{.DOCKER_TAG}} .
        --push
    vars:
      DOCKER_TAG: latest
      DOCKER_IMAGE_NAME: pandoc
      DOCKER_PLATFORMS: linux/amd64
