# https://taskfile.dev

version: '3'

vars:
  tag: latest
  IMAGE_NAME_PANDOC: pandoc

tasks:
  build:
    run: once
    desc: Build Image.
    cmds:
      - docker build --file Dockerfile --tag {{.DOCKER_ORGANIZATION}}/{{.IMAGE_NAME_PANDOC}}:{{.tag}} .

  publish:
    deps: [build]
    desc: Publish Image.
    cmds:
      - docker push {{.DOCKER_ORGANIZATION}}/{{.IMAGE_NAME_PANDOC}}:{{.tag}}
