# https://taskfile.dev

version: '3'

vars:
  tag: latest
  IMAGE_NAME_DIRSEARCH: dirsearch

tasks:
  build:
    desc: Build Image.
    run: once
    cmds:
      - docker build --file Dockerfile --tag {{.DOCKER_ORGANIZATION}}/{{.IMAGE_NAME_DIRSEARCH}}:{{.tag}} .

  publish:
    desc: Publish Image.
    deps:
      - build
    run: once
    cmds:
      - docker push {{.DOCKER_ORGANIZATION}}/{{.IMAGE_NAME_DIRSEARCH}}:{{.tag}}
